language: python

python:
  - "2.7"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libnetcdf-dev
 - sudo apt-get install libhdf5-dev
 - pip install -r requirements.txt --use-mirrors

# command to run tests
script: python ./TDSter.py --verbosity 1
